export enum LeadsActionTypes {
    API_RESPONSE_SUCCESS = '@leads/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR = '@leads/API_RESPONSE_ERROR',
    CREATE_NEW_LEAD = '@leads/CREATE_NEW_LEAD',
    GET_ALL_LEADS = '@leads/GET_ALL_LEADS',
    DELETE_LEAD = '@leads/DELETE_LEAD',
    RESET_LEADS = '@leads/RESET_LEADS',
    UPDATE_COMMENTS = '@leads/UPDATE_COMMENTS',
    UPDATE_STATUS = '@leads/UPDATE_STATUS',
}
