export const CONSTANTS = {
    API_URLS: {
        AVATAR_IMAGE_URL: "https://cdn-icons-png.flaticon.com/512/3607/3607444.png",

        // BASE: "https://crm-backend-78e9.onrender.com",

        BASE: "http://127.0.0.1:8000",

        Dashboard: "/dashBoard/",
        SALES: "/sales/",
        LOGIN: "/user/login",
        PROFILE: "/user/profile",
        USER_SEACRH: "/user/search/",
        ADD_Employeee: "/user/register",
        Reset_password: "/user/reset-password",
        getEmployee: '/user/users',
        UPDATE_EMPLOYEE: "/user/update",
        getEmployeeByid: '/user/user',
        deleteEmployee: `/user/delete/`,
        role: "/role",
        getInvoice: '/invoice/',
        getCategory: '/category',
        target: "/target/",
        Gettarget: "/tracking/get",
        comission: "/comission/",
        customer: '/customer/',
        platform: '/platform/add',
        UpdatePlatform: '/platform/update',
        deletePlatform: '/platform/delete',
        Get_Platform: '/platform',
        project: '/project',
        Createproject: '/project/create',
        CreateBoard: '/project/createBoard',
        EditBoard: '/project/EditBoard',
        DeleteBoard: '/project/DeleteBoard/',
        task: '/project/Task',
        uploadDoc: '/project/uploadDoc',
        editProject: '/project/editProject',
        sendComments: '/project/comments',
        sendCommentsReply: '/project/comments/replies/',
        AddTeamMembers:"/project/add-team-members",
        RemoveTeamMember:"/project/remove-team-member",
        Droptask: '/project/DropTask',
        GetBoard: '/project/board/',
        portal: '/portal',
        edit: '/edit',
        projectMilestone: '/milestone',
        lead: '/lead',
        editLead: '/lead/update',
        AddLead: '/lead/add',
        Addbids: "/bids/add",
        Todaybids: "/bids/today",
        Monthbids: "/bids/month",
        deleteLead: '/lead/delete',
        expenseCategory: '/expense/category',
        AddExpense: '/expense/add',
        getReport: "/report/",
        UpdateExpense: '/expense/update/',
        GetExpense: '/expense/',
        DeleteExpense: '/expense/delete/',
        banks: '/banks',
        milestone: '/milestone',
        vendorCategory: '/vendor/category',
        vendor: '/vendor',
        vendorPayment: '/vendor/payment',
        attendancePerMonth: '/attendance/month',
        UserMailAdd: '/userMails/add',
        UserMail: '/userMails/',
        GetEmail: "/MailServices/emails/",
        GetSendEmail: "/MailServices/emails/sent/",
        SendEmail: "/MailServices/send-email/",
        card: '/card',

    }
} 