export const CONSTANTS = {
    API_URLS: {
        // BASE: "http://127.0.0.1:8000/api/",
        BASE: "http://127.0.0.1:8000/",
        // BASE: "https://crmupd.pixelssoft.com/api/",
        LOGIN: "user/login",
        PROFILE: "user/profile",
        ADD_Employeee: "user/register",
        getEmployee: 'user/users',
        UPDATE_EMPLOYEE: "user/update",
        getEmployeeByid: 'user/user',
        deleteEmployee: `user/delete`,
        role: "role",
        getInvoice: 'invoice',
        getCategory: 'category',
        customer: 'customer',
        platform: 'platform/add',
        UpdatePlatform: 'platform/update',
        deletePlatform: 'platform/delete',
        Get_Platform: 'platform',
        project: 'project',
        edit: 'edit',
        projectMilestone: 'milestone?project=',
        lead: 'lead',
        editLead: 'lead/update',
        AddLead: 'lead/add',
        deleteLead: 'lead/delete',
        expenseCategory: 'expense/category',
        expense: 'expense',
        milestone: 'milestone',
        vendorCategory: 'vendor/category',
        vendor: 'vendor',
        vendorPayment: 'payment/vendor',
    }
} 