export const CONSTANTS = {
    API_URLS: {
        // BASE: "http://127.0.0.1:8000/api/",
        // BASE: "http://127.0.0.1:8000/",
        BASE: "https://crmupd.pixelssoft.com/api/",
        LOGIN: "user/login",
        ADD_Employeee: "user/register",
        getEmployee: 'user',
        deleteEmployee: `user/`,
        role: "role",
        getInvoice: 'invoice',
        getCategory: 'category',
        customer: 'customer',
        platform: 'platform',
        project: 'project',
        edit: 'edit',
        projectMilestone: 'milestone?project=',
        lead: 'lead',
        expenseCategory: 'expense/category',
        expense: 'expense',
        milestone: 'milestone',
        vendorCategory: 'vendor/category',
        vendor: 'vendor',
        vendorPayment: 'payment/vendor',
    }
} 