export const CONSTANTS = {
    API_URLS: {
        // BASE: "http://127.0.0.1:8000/api/",
        // BASE: "https://crm-backend-78e9.onrender.com/",
        BASE: "https://ideal-computing-machine-4r4ww49w9g535g4r-8000.app.github.dev/",
        // BASE: "http://127.0.0.1:8000/",
        // BASE: "https://crmupd.pixelssoft.com/api/",
        LOGIN: "user/login",
        PROFILE: "user/profile",
        USER_SEACRH: "user/search/",
        ADD_Employeee: "user/register",
        getEmployee: 'user/users',
        UPDATE_EMPLOYEE: "user/update",
        getEmployeeByid: 'user/user',
        deleteEmployee: `user/delete/`,
        role: "role",
        getInvoice: 'invoice',
        getCategory: 'category',
        customer: 'customer',
        platform: 'platform/add',
        UpdatePlatform: 'platform/update',
        deletePlatform: 'platform/delete',
        Get_Platform: 'platform',
        project: 'project',
        Createproject: 'project/create',
        CreateBoard: 'project/createBoard',
        EditBoard: 'project/EditBoard',
        DeleteBoard: 'project/DeleteBoard/',
        task: 'project/Task',
        uploadDoc: 'project/uploadDoc',
        editProject: 'project/editProject',
        sendComments: 'project/comments',
        sendCommentsReply: 'project/comments/replies/',
        Droptask: 'project/DropTask',
        GetBoard: 'project/board/',
        portal: 'portal',
        edit: 'edit',
        projectMilestone: 'milestone',
        lead: 'lead',
        editLead: 'lead/update',
        AddLead: 'lead/add',
        Addbids: "bids/add",
        Todaybids: "bids/today",
        Monthbids: "bids/month",
        deleteLead: 'lead/delete',
        expenseCategory: 'expense/category',
        expense: 'expense',
        banks: 'banks',
        milestone: 'milestone',
        vendorCategory: 'vendor/category',
        vendor: 'vendor',
        vendorPayment: 'payment/vendor',
        attendancePerMonth: 'attendance/month',
    }
} 